### ISSUE TITLE
Gravity One Theme

### ISSUE THREAD

**Issue by intothevoid0** [frankyonnetti/gravity-vscode-theme#1]
I'm not sure if it's possible, but is there any way in VS Code to set the styling similar to Gravity One in Sublime?

**Comment by frankyonnetti** [comment]
Sorry, I only created the dark Monokai theme. I don't have plans to port Gravity One to VS Code.

**Comment by intothevoid0** [comment]
No problem, thanks for getting back to me. I understand that it isn't in the cards. If you have a moment, could you highlight a few distinctions in the Gravity One theme? Or is it best to just review the details of `One Dark Gravity.sublime-color-scheme`?

**Comment by frankyonnetti** [comment]
It's just a matter of replacing the color values with the ones from One Dark Gravity.

Here are the docs you need:
https://code.visualstudio.com/api/extension-guides/color-theme
https://code.visualstudio.com/api/references/theme-color
